apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: goldenpath-idp-backstage
  description: Backstage Developer Portal for Golden Path IDP
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: mikeybeezy/goldenpath-idp-backstage
spec:
  type: service
  owner: platform-team
  lifecycle: active
